language: python
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=pypy
    - TOXENV=flake8
install:
    - pip install tox --use-mirrors
    - pip install -q coveralls --use-wheel
script:
    - tox
after_success:
    - coveralls
